import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const cpinfoPath = path.join(rootDir, "cpinfo.md");
const outputPath = path.join(rootDir, "data", "pair-profiles.ts");

const source = fs.readFileSync(cpinfoPath, "utf8");
const resultMatch = source.match(
  /export const results: ResultProfile\[] = (\[[\s\S]*?\n\]);/,
);

if (!resultMatch) {
  throw new Error("Unable to locate `results` in cpinfo.md.");
}

const profiles = Function(`"use strict"; return (${resultMatch[1]});`)();

if (!Array.isArray(profiles) || profiles.length === 0) {
  throw new Error("Parsed cpinfo results are empty.");
}

const resultIds = profiles.map((profile) => profile.id);
const traitTags = [...new Set(profiles.flatMap((profile) => profile.scoringHints))];

const output = `// This file is generated from cpinfo.md by scripts/sync-cpinfo.mjs.
// Do not edit this file manually.

export const RESULT_IDS = ${JSON.stringify(resultIds, null, 2)} as const;

export const TRAIT_TAGS = ${JSON.stringify(traitTags, null, 2)} as const;

export const PAIR_PROFILES = ${JSON.stringify(profiles, null, 2)} as const;

export type PairProfileSource = (typeof PAIR_PROFILES)[number];
`;

fs.writeFileSync(outputPath, output);
